language: node_js

node_js:
  - 'lts/*'
  - '8'
  - 'node'

os:
  - windows
  - osx
  - linux

sudo: false

script:
 - npm test

after_success:
 - npm i -g codecov && npm run coverage && codecov

cache:
  directories:
    - node_modules